# Reshaping data in Python

## 1. Reshaping data in NumPy
NumPy has a number of nice reshaping commands. It is in the object's shape where Numpy really shines. NumPy is great at handling a large number of dimensions of object data. Pandas becomes more clunky the more hierarchical indices are added. However, NumPy is limited by the content of its objects in that all numpy arrays must have the same type of content.

### 1.1 Transpose
Let the matrix `A` be defined as follows.

In [13]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print(A.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [2]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [3]:
A.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

The transpose function is much more flexible in that you can combine elements of reshaping the array and transposing along certain dimensions.

### 1.2 np.reshape()
Sometimes you want to change an array's shape. The reshape command is very flexible. The key concept to keep in mind is that NumPy arrays are row-major (as with the C programming language). When flattening or reshaping an array, Numpy starts counting in the first row along each of the columns, then proceeds to the second row, and follows that pattern along each of the other dimensions.

In [5]:
A.reshape((1, 6))

array([[1, 2, 3, 4, 5, 6]])

In [6]:
A.reshape((6,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [7]:
print(A.reshape((1, 2, 3)))
print(A.reshape((1, 2, 3)).shape)

[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)


In [8]:
A.reshape((1, 2, 3))[0, :, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
A.reshape((1, 2, 3))[0, :, 0]

array([1, 4])

In [ ]:
A.reshape((1, 2, 3))[0, :, 1]

### 1.3 Vectorize: np.ravel() and np.flatten()
It is often valuable to vectorize (make one-dimensional) a multi-dimensional array. A major reason for this is that computers are much faster at working with one-dimensional arrays than with arrays of more-than-one dimension. The two main functions for doing this are `np.ravel()` and `np.flatten()` they both do almost the same thing. The only difference is that `ravel()` produces a vectorized version of the original unvectorized array for which changing values of the `ravel()` vector might change elements of the original array. `flatten()` creates a vectorized copy of the original array. So no changes of the `flatten()` vector would ever change the original array.

In [10]:
A.flatten()

array([1, 2, 3, 4, 5, 6])

In [12]:
b = A.ravel()

array([[100,   2,   3],
       [  4,   5,   6]])

### 1.4 Stacking
The stacking commands are very easy to use in numpy. The main commands are `np.hstack()`, `np.vstack()`, and `np.tile()`.

The function `np.hstack()` stacks arrays horizontally. Each array must have the same shape in its first dimension. For example, define the arrays A, B, and C in the following way.

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
B = np.array([-1, -2, -3])
B

array([-1, -2, -3])

In [16]:
C = np.array([[10, 20], [30, 40], [50, 60]])
C

array([[10, 20],
       [30, 40],
       [50, 60]])

The following won't work because they are not comformable.

In [ ]:
np.hstack((A, B))

But the following will work.

In [17]:
np.hstack((C, A.T))

array([[10, 20,  1,  4],
       [30, 40,  2,  5],
       [50, 60,  3,  6]])

However, the following will not work because `B.T` is not defined for a one-dimensional vector. For this, we will have to use the `.reshape()` method.

In [20]:
B = B.reshape(3, 1)
np.hstack((C, A.T, B))

array([[10, 20,  1,  4, -1],
       [30, 40,  2,  5, -2],
       [50, 60,  3,  6, -3]])

In [21]:
B.T.shape

(1, 3)

In [ ]:
np.hstack((C, A.T, B.reshape((3, 1))))

The function `np.vstack()` stacks arrays vertically. Each array must have the same shape in its second dimension (across columns). We use the same arrays A, B, and C as in the preceding `np.hstack()` example.

In [ ]:
A

In [ ]:
B

In [ ]:
C

Note that the following `np.vstack()` command works with the one-dimensional vector `B`.

In [ ]:
np.vstack((A, B))

We could vertically stack all three arrays in the following way.

In [ ]:
np.vstack((A, B, C.T))

Finally, the `np.tile()` command is a useful function for copying arrays of any dimension into other any dimension. This is a very flexible function.

The following command takes a one-dimensional (3,) vector, reshapes it into a 1 x 1 x 3 and copies it down two rows and across three columns.

In [25]:
F = np.array([1, 2, 3])
F
G = np.tile(F.reshape((1, 1, 3)), (2, 3, 1))
G

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [ ]:
G[:, :, 0]

In [ ]:
G[:, :, 1]

## 2. Reshaping data in Pandas
NumPy has a number of nice reshaping commands. It is in the object's shape where Numpy really shines. NumPy is great at handling a large number of dimensions of object data. Pandas becomes more clunky the more hierarchical indices are added. However, NumPy is limited by the content of its objects in that all numpy arrays must have the same type of content.

### 2.1. Combining and merging data sets
Focus on three functions.
* `pandas.merge`: connects rows in DataFrames based on one or more keys. This is pandas way of implementing database *join* operations. This is the main entry point for using these algorithms on your data.
* `pandas.concat`: stacks together objects along an axis.
* `combine_first`: instance method enables splicing together overlapping data to fill in missing values in one object with values from another.

#### 2.1.1. pd.merge()

In [26]:
import pandas as pd
from pandas import DataFrame, Series

df1 = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1': range(7)}) 
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [27]:
df2 = DataFrame({'key': ['a', 'b', 'd'], 'data2': range(3)})
df2

data2 key
0      0   a
1      1   b
2      2   d

The following is a *many-to-one* merge. `df1` has multiple values for `a` (2, 4, 5) while `df2` has only one value for `a` (0). And `df2` has multiple values for `b` (0, 1, 6) while `df2` has only one value for `b` (1).

In [28]:
pd.merge(df1, df2)

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

Two things to note.
* If you don't specify which column to join on, `merge` uses the overlapping column names as the keys--in this case, `key`.
* This command leaves out the `key` of `b` from `df2` and the `key` of `c` from `df1`. This is because these `key` values only occur in one, not both, of the DataFrames being merged.

It is good practice to specify the column on which to merge.

In [29]:
pd.merge(df1, df2, on='key')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

If the column names are different in each object, you can specify them separately.

In [30]:
df3 = DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1': range(7)})
df3

data1 lkey
0      0    b
1      1    b
2      2    a
3      3    c
4      4    a
5      5    a
6      6    b

In [31]:
df4 = DataFrame({'rkey': ['a', 'b', 'd'], 'data2': range(3)})
df4

data2 rkey
0      0    a
1      1    b
2      2    d

In [32]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

Note again that this only includes value for which the `key` is found in both datasets. This is called an `inner` join. Other possible options are `left`, `right`, and `outer`. The `inner` join takes the intersection of keys, the `outer` join takes the union of keys.

In [33]:
pd.merge(df1,df2, how='outer')

data1 key  data2
0    0.0   b    1.0
1    1.0   b    1.0
2    6.0   b    1.0
3    2.0   a    0.0
4    4.0   a    0.0
5    5.0   a    0.0
6    3.0   c    NaN
7    NaN   d    2.0

*Many-to-many* merges form the Cartesian product of the observations or rows.

In [34]:
df5 = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)})
df5

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   b

In [35]:
df6 = DataFrame({'key': ['a', 'b', 'a', 'b', 'd'], 'data2': range(5)})
df6

data2 key
0      0   a
1      1   b
2      2   a
3      3   b
4      4   d

In [36]:
pd.merge(df5, df6, on='key', how='left')

data1 key  data2
0       0   b    1.0
1       0   b    3.0
2       1   b    1.0
3       1   b    3.0
4       2   a    0.0
5       2   a    2.0
6       3   c    NaN
7       4   a    0.0
8       4   a    2.0
9       5   b    1.0
10      5   b    3.0

Notice the following:
* Because it was a `left` merge, it included all the values in `df5` but not all of the values in `df6`.
* Since there were 3 `b` rows in `df5` and 2 `b` rows in `df6`, the merged DataFrame has 6 `b` rows.

To merge with multiple keys, pass a list of column names.

In [37]:
df7 = DataFrame({'key1': ['foo', 'foo', 'bar'],
                 'key2': ['one', 'two', 'one'],
                 'lval': [1, 2, 3]})
df7

key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [38]:
df8 = DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                 'key2': ['one', 'one', 'one', 'two'],
                 'rval': [4, 5, 6, 7]})
df8

key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [39]:
pd.merge(df7, df8, on=['key1', 'key2'], how='outer')

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

When merging data, you often have to deal with column names that overlap. the merge command will automatically give suffixes to column names that are not the `key` column that have the same name. Otherwise, you can use the `suffixes` option to specify the suffix labels.

In [ ]:
pd.merge(df7, df8, on='key1')

In [ ]:
pd.merge(df7, df8, on='key1', suffixes=('_left', '_right'))

A more common practice is to merge using a DataFrame's index as the merge key. You can use `left_index=True` or `right_index=True` or both.

In [ ]:
df9 = DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'], 'value': range(6)})
df9

In [ ]:
df10 = DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])
df10

In [ ]:
pd.merge(df9, df10, left_on='key', right_index=True)

You can use the indices on both DataFrames of the merge as the merge keys, and you can deal with hierarchical key merges.

#### 2.1.2. pd.join()
The `pd.join()` method is a more convenient function for merging by index than `pd.merge`. It can also be used to comine together many DataFrame objects having the same or similar indices but not overlapping columns.

In [ ]:
df11 = DataFrame([[1, 2], [3, 4], [5, 6]], index=['a', 'b', 'c'], columns=['Ohio', 'Nevada'])
df11

In [ ]:
df12 = DataFrame([[7, 8], [9, 10], [11, 12], [13, 14]],
                 index=['b', 'c', 'd', 'e'], columns=['Missouri', 'Alabama'])
df12

In [ ]:
df11.join(df12, how='outer')

The following command joins the index of the calling DataFrame with a column of the passed DataFrame.

In [ ]:
df9.join(df10, on='key')

### 2.2. Reshaping, pivoting, and groupby

#### 2.2.1. Reshaping with hierarchical indexing

In [ ]:
data = DataFrame(np.arange(6).reshape((2, 3)),
                 index=pd.Index(['Ohio', 'Colorado'], name='state'),
                 columns=pd.Index(['one', 'two', 'three'], name='number'))
data

The `stack()` method on this data pibots the columns into the rows, producing a hierarchically indexed Series.

In [ ]:
result = data.stack()
result

From a hierarchically indexed Series, you can rearrange the data back into a DataFrame with `unstack()`. [I don't know what the warning is coming from.]

In [ ]:
result.unstack()

By default, the innermost level is unstacked (same with `stack`). You can unstack a different level by passing a level number or name.

In [ ]:
result.unstack(0)

In [ ]:
result.unstack('state')

#### 2.2.2. Pivoting between "long" and "wide"
Data is often saved in "long" format in which each observation is a characteristic of a particular key. That is, the "long" format contains multiple observations on a given key. "Wide" format is a reshaping of the data in which each observation on a given key becomes a separate column of the data such that the new DataFrame has only one observation for each unique value of the key.

### 2.3. Data transformation
asdf

## References

* McKinney, Wes, Python for Data Analysis, O'Reilly Media, Inc. (2013).
* [Python labs](http://www.acme.byu.edu/?page_id=2067), Applied and Computational Mathematics Emphasis (ACME), Brigham Young University.